urls.py
from django.urls import path
from . import views

app_name='blog'

urlpatterns = [
    # path("", views.post_list, name='post_list'),
    path("", views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share')
]

models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


import string


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='опубликовано')


class Post(models.Model):
    STATUS_CHOICE = (
        ('черновик', 'Черновик'),
        ('опубликовано', 'Опубликовано')
    )
    title = models.CharField(max_length=250, verbose_name="Заголовок")
    slug = models.SlugField(max_length=250, unique_for_date='publish', verbose_name="Заголовок(лат)")
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts', verbose_name="Автор")
    body = models.TextField(verbose_name="Текст")
    image = models.ImageField(verbose_name="Изображение", default='/static/images/default_image.png',
                              upload_to="blog/static/images")
    viewsUser = models.IntegerField(default=0, editable=False)
    sharesUser = models.IntegerField(default=0, editable=False)
    publish = models.DateTimeField(default=timezone.now, verbose_name="Дата публикации")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated = models.DateTimeField(auto_now=True, verbose_name="Дато обновления")
    status = models.CharField(max_length=50, choices=STATUS_CHOICE, default='draft', verbose_name="Статус")
    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])

    def get_img_url(self):
        return self.image.name.replace('blog', '')


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80, verbose_name="Имя")
    email = models.EmailField(verbose_name="Email")
    body = models.TextField(verbose_name="Комментарий")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated = models.DateTimeField(auto_now=True, verbose_name="Дато обновления")
    active = models.BooleanField(default=True, verbose_name="Активный")

    class Meta:
        ordering = ('created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25, label="Имя")
    email = forms.EmailField(label="E-mail")
    to = forms.EmailField(label="E-mail To")
    comments = forms.CharField(required=False, widget=forms.Textarea, label="Комментарий")

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Post, Comment
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_list(request):
    object_list = Post.published.all()
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page': page, 'posts': posts, 'paginator': paginator})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post,
                             slug=post,
                             status="опубликовано",
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm
    post.viewsUser += 1
    post.save()
    return render(request, 'blog/post/detail.html', {'post': post,
                                                     'comments': comments,
                                                     'new_comment': new_comment,
                                                     'comment_form': comment_form})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status="опубликовано")
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) рекомендуем прочитать"{}" '.format(cd['name'], cd['email'], post.title)
            message = 'Прочитать "{}" на {}\n\n{} для вас есть комментариий: {}'.format(post.title, post_url,
                                                                                        cd['name'], cd['comments'])
            send_mail(subject, message, 'shareservicemyblog@gmail.com', [cd['to']])
            sent = True
            post.sharesUser += 1
            post.save()
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})

templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">
</head>

<body>
    <header class="header">
        <div class="container">
            <div class="header_body">
                <ul class="header_list">
                    <li>
                        <a href="/blog" class="header_link">Главная</a>
                    </li>
                </ul>
            </div>
        </div>
    </header>
    <div class="main_content" id="content">
        <div class="container">
            {% block content %}{% endblock %}
        </div>
    </div>
</body>

</html>

templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
<div class="post_card_detail">
    <div class="post_card_content">
        <h2 class="post_title">
            <a>{{ post.title }}</a> 
        </h2>
        <span class="post_author">
            <h4>Опубликовал:</h4>{{ post.author }}
        </span>
        <p class="post_date">Дата публикации: {{ post.publish }}</p>
        <img class="post_img" src={{ post.get_img_url }}>
        <div class="post_text">
            {{ post.body|linebreaks }}
        </div>
        {% with comments.count as total_comments %}
                <h2>{{ total_comments }} Комментарий</h2>
        {% endwith %}
        {% for comment in comments %}
                <div class="comment">
                    <p class="info">
                        <h4>{{ comment.name }}</h4>
                        <span>{{ comment.created }}</span>
                    </p>
                    {{ comment.body|linebreaks }}
                </div>
        {% empty %}
            <p>Здесь пока нет комментариев</p>
        {% endfor %}
        <div class="post_comment">
            <h2>Добавить комментарий</h2>
            <form action="." method="post">
                {{ comment_form.as_p }}
                {% csrf_token %}
                <p><input type="submit" value="Add comment"></p>
            </form>
        </div>
        <p>
            <a class="button_share" href="{% url "blog:post_share" post.id %}">Поделится постом</a>
        </p>
    </div>
</div>
{% endblock %}

templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}My Blog{% endblock %}
{% block content %}

{% for post in posts %}
<div class="post_card" onclick="location.href='{{ post.get_absolute_url }}';">
        <div class="post_card_content">
            <h2 class="list_title">
                <a class="list_title" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h2>
            <span class="list_author">
                <h4>Опубликовал:</h4>{{ post.author }}
            </span>
            <p class="list_date">Дата публикации: {{ post.publish }}</p>
            <img class="list_img" src={{ post.get_img_url }}>
            <div class="post_text">
                {{ post.body|truncatewords:30|linebreaks }}
            </div>
            <div class="post_info">
                <p><i class="fas fa-eye"></i>{{post.viewsUser}}</p>
                <p><i class="fas fa-share"></i>{{post.sharesUser}}</p>
            </div>

        </div>

</div>
{% endfor %}
{% include "pagination.html" with page=page_obj %}
{% endblock %}

templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Поделись постом!{% endblock %}
{% block content %}
{% if sent %}
    <h1>E-mail был отправлен!</h1>
    <p>"{{ post.title }}" был успешно отправлен на {{ form.cleaned_data.to }}.</p>
{% else %}
    <div class="form_share">
        <h1>Поделится с постом</h1>
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input class="button_submit" type="submit" value="Send e-mail">
        </form>
    </div>
{% endif %}
{% endblock %}

templates/pagination.html
{% load static %}
<head>
    <link href="{% static 'css/pagination.css' %}" rel="stylesheet">
</head>
<div class="pagination">
<!--    <span class="step-links">-->
<!--        {% if page.has_previous %}-->
<!--            <a href="?page={{page.previous_page_number}}">Previous</a>-->
<!--        {% endif %}-->
<!--        <span class="current">-->
<!--            Page {{ page.number }} of {{ page.paginator.num_pages }}.-->
<!--        </span>-->
<!--        {% if page.has_next %}-->
<!--            <a href="?page={{ page.next_page_number }}">Next</a>-->
<!--        {% endif %}-->
<!--    </span>-->
        {% for pageIn in paginator %}
            {% if page.number == pageIn.number %}
                <a>{{pageIn.number}}</a>
            {% else %}
                <a href="?page={{pageIn.number}}">{{pageIn.number}}</a>
            {% endif %}
        {% endfor %}
</div>